### ISSUE TITLE
User can search for a games discussion board by name.

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/final-project#1]
## 💰 Motivation

The user will see be able to see  games related to what they searched for.

## 📐 Plan

Make a Get request to an API and insert the response onto the users screen.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/54919527/114221150-c996b600-9921-11eb-987c-909f16335415.png)

![image](https://user-images.githubusercontent.com/54919527/114221223-e16e3a00-9921-11eb-8feb-0499066302cb.png)

## ✅ Task List

- [x] Setup the basic structure for the program.
- [x] Create the header component.
- [x] Create a basic structure of the Search page.
- [x] Create a component for an individual game.
- [x] Make sure all elements have proper CSS.
- [x] Add a Form element that takes user input.
- [x] Make an API call for the individual name.
- [x] Output the response of the API onto the screen.
- [x] Check for any useless code.
- [x] Final check that code works as intended too.
