### ISSUE TITLE
Polish Checklist

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/final-project#17]
- [x] Verify the consistency of your site's theme.
- [x] Verify the site's HTML has good semantics. For any changes to the HTML structure, update the CSS as-needed to prevent the UI from breaking.
- [x] Verify the site's layout fits and effectively uses space on all commonly-used device sizes, including:
- [x] Verify that each interactive element on the site looks and feels interactive:
- [x] Verify that each API request (that isn't part of initial page load) handles network wait times and failures gracefully (test using inspector Network tab):
- [x] Verify that the following common issues are addressed:
- [x] For each page, run the automatic Accessibility tests (and only the those tests) in the [Lighthouse testing tool](https://developers.google.com/web/tools/lighthouse#devtools) on both Mobile and Desktop, fixing each issue that comes up. Re-run it until all issues are addressed.
