### ISSUE TITLE
User can see a list of the top discussion boards with the most posts.

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/final-project#2]
## 💰 Motivation

The user will see be able to see a list of games with the most posts on its thread.

## 📐 Plan

Make a fetch request (GET) to the server , then the server will send a query to the database and return the top 
threads with the most posts.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/54919527/113643373-0b301400-9637-11eb-9c23-e6e72ab52b06.png)

## ✅ Task List

- [ ] Create a function that sends a fetch to the database 
- [ ] Display the results onto the screen.
- [ ] Fix CSS for the results
