### ISSUE TITLE
User can see a games title, description and image.

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/final-project#3]
## 💰 Motivation

The user will see be able to see  a single game with its title, description and an image.

## 📐 Plan

Make a Get request to an API and insert the response onto the users screen.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/54919527/114470630-1093de00-9ba4-11eb-96d5-d9351a3465e8.png)

![image](https://user-images.githubusercontent.com/54919527/114470571-f9ed8700-9ba3-11eb-9aba-117ebb80c27c.png)

## ✅ Task List

- [x] Create a page for a game that show title description and an image.
- [x] Use CSS on new page
- [x] Make individual game components clickable.
- [x] Implement hash based URLs.
- [x] Check for useless code.
- [x] Final check entire program.
