### ISSUE TITLE
User can post on the discussion board. 

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/final-project#4]
## 💰 Motivation

The user will see be able to post a message onto the database and view it on screen.

## 📐 Plan

Get input from the client, send a fetch request (POST) to the server, send a query to the database.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/54919527/115263103-fac57200-a0e9-11eb-8c05-76a0de20d065.png)

![image](https://user-images.githubusercontent.com/54919527/115263186-103a9c00-a0ea-11eb-9004-7892d08f01f4.png)

## ✅ Task List

- [x] Create a page that has the discussion board of that game.
- [x] Connect  the enter thread button to the discussion board page.
- [x] Create the UI for discussion board.
- [x] Create a post and push it into the database
- [x] Create a component of a single post.
- [x] Make a function that retrieves data from the table.
