### ISSUE TITLE
User can reply to other users' posts.

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/final-project#5]
## 💰 Motivation

The user will see be able to see  reply to another users post on a thread.

## 📐 Plan

Get input from the client, send a fetch request (POST) to the server, send a query to the database and display the return.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/54919527/113752300-a5d53500-96c1-11eb-98bf-e3cb656ff86e.png)

## ✅ Task List

- [x] Fix database so that there is an entry for a response.
- [x] Change the API endpoint so that it can determine if it is a reply or a post.
- [x] Create a component that attaches to the main post.
