### ISSUE TITLE
 User can add different discussion boards to their favorites list.

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/final-project#6]
## 💰 Motivation

The user will see be able to add a games thread to their favorites list.

## 📐 Plan

Get input from the client, send a fetch request (POST) to the server, send a query to the database and then change the color when the return came back with no errors.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/54919527/114764138-6ee1cd80-9d18-11eb-94d4-c86be4c692f5.png)
![image](https://user-images.githubusercontent.com/54919527/114764254-92a51380-9d18-11eb-9b3c-99b171606211.png)

## ✅ Task List

- [x] Create a table for the user where their favorite games are stored.
- [x] Make a function that sends a query to add a game to the database
- [x] Make a function that sends a query to remove a game from the database
- [x] Before listing games check to see if they are in the database and make the icon blue
- [x] Check for unused code.
