### ISSUE TITLE
User can see a list of their favorite discussion boards.

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/final-project#7]
## 💰 Motivation

The user will see be able to see a list of their favorite game threads.

## 📐 Plan

 Send a fetch request (GET) to the server, send a query to the database and display the return.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/54919527/114920648-81263f00-9dde-11eb-9c6f-180544a77b29.png)
![image](https://user-images.githubusercontent.com/54919527/114920673-871c2000-9dde-11eb-978d-2e0e1ba16243.png)

## ✅ Task List

- [x] Create a modal for the menu
- [x] Link all pages to the modal
- [x] Use or create a function that returns a list of all the games in the database
- [x] Display the list.
- [x] Check for useless code
